interface StringConstants {
  [key: string]: string;
}

interface NumberConstants {
  [key: string]: number;
}

export const TILE_SIZE = 16;
export const ANIM_FRAMERATE = 2;
export const API_URL = "https://api.activategame.dev/";

export const keys: StringConstants = {
  SCENE_BOOT: "SCENE_BOOT",
  SCENE_NEW_GAME: "SCENE_NEW_GAME",
  SCENE_DUNGEON: "SCENE_DUNGEON",
  SCENE_MENU: "SCENE_MENU",

  TILES_DUNGEON: "TILES_DUNGEON",

  SPRITES_FONT: "SPRITES_FONT",
  SPRITES_FX: "SPRITES_FX",
  SPRITES_INTERFACE: "SPRITES_INTERFACE",
  SPRITES_ITEMS: "SPRITES_ITEMS",
  SPRITES_MONSTERS: "SPRITES_MONSTERS",
  SPRITES_PORTRAITS: "SPRITES_PORTRAITS",
  SPRITES_DUNGEON: "SPRITES_DUNGEON",

  ANIM_PLAYER_NORTH: "ANIM_PLAYER_NORTH",
  ANIM_PLAYER_SOUTH: "ANIM_PLAYER_SOUTH",
  ANIM_PLAYER_EAST: "ANIM_PLAYER_EAST",
  ANIM_PLAYER_WEST: "ANIM_PLAYER_WEST",

  ANIM_SKELETON_NORTH: "ANIM_SKELETON_NORTH",
  ANIM_SKELETON_SOUTH: "ANIM_SKELETON_SOUTH",
  ANIM_SKELETON_EAST: "ANIM_SKELETON_EAST",
  ANIM_SKELETON_WEST: "ANIM_SKELETON_WEST",

  ANIM_SKELETON_GUARD_NORTH: "ANIM_SKELETON_GUARD_NORTH",
  ANIM_SKELETON_GUARD_SOUTH: "ANIM_SKELETON_GUARD_SOUTH",
  ANIM_SKELETON_GUARD_EAST: "ANIM_SKELETON_GUARD_EAST",
  ANIM_SKELETON_GUARD_WEST: "ANIM_SKELETON_GUARD_WEST",

  ANIM_SPIRIT_NORTH: "ANIM_SPIRIT_NORTH",
  ANIM_SPIRIT_SOUTH: "ANIM_SPIRIT_SOUTH",
  ANIM_SPIRIT_EAST: "ANIM_SPIRIT_EAST",
  ANIM_SPIRIT_WEST: "ANIM_SPIRIT_WEST",

  ANIM_LICH_NORTH: "ANIM_LICH_NORTH",
  ANIM_LICH_SOUTH: "ANIM_LICH_SOUTH",
  ANIM_LICH_EAST: "ANIM_LICH_EAST",
  ANIM_LICH_WEST: "ANIM_LICH_WEST",

  ANIM_GOBLIN_NORTH: "ANIM_GOBLIN_NORTH",
  ANIM_GOBLIN_SOUTH: "ANIM_GOBLIN_SOUTH",
  ANIM_GOBLIN_EAST: "ANIM_GOBLIN_EAST",
  ANIM_GOBLIN_WEST: "ANIM_GOBLIN_WEST",

  ANIM_GOBLIN_GUARD_NORTH: "ANIM_GOBLIN_GUARD_NORTH",
  ANIM_GOBLIN_GUARD_SOUTH: "ANIM_GOBLIN_GUARD_SOUTH",
  ANIM_GOBLIN_GUARD_EAST: "ANIM_GOBLIN_GUARD_EAST",
  ANIM_GOBLIN_GUARD_WEST: "ANIM_GOBLIN_GUARD_WEST",

  ANIM_GOBLIN_MAGE_NORTH: "ANIM_GOBLIN_MAGE_NORTH",
  ANIM_GOBLIN_MAGE_SOUTH: "ANIM_GOBLIN_MAGE_SOUTH",
  ANIM_GOBLIN_MAGE_EAST: "ANIM_GOBLIN_MAGE_EAST",
  ANIM_GOBLIN_MAGE_WEST: "ANIM_GOBLIN_MAGE_WEST",

  ANIM_DRACULA_NORTH: "ANIM_DRACULA_NORTH",
  ANIM_DRACULA_SOUTH: "ANIM_DRACULA_SOUTH",
  ANIM_DRACULA_EAST: "ANIM_DRACULA_EAST",
  ANIM_DRACULA_WEST: "ANIM_DRACULA_WEST",

  ANIM_WATER_ELEMENTAL_NORTH: "ANIM_WATER_ELEMENTAL_NORTH",
  ANIM_WATER_ELEMENTAL_SOUTH: "ANIM_WATER_ELEMENTAL_SOUTH",
  ANIM_WATER_ELEMENTAL_EAST: "ANIM_WATER_ELEMENTAL_EAST",
  ANIM_WATER_ELEMENTAL_WEST: "ANIM_WATER_ELEMENTAL_WEST",

  ANIM_BEHOLDER_NORTH: "ANIM_BEHOLDER_NORTH",
  ANIM_BEHOLDER_SOUTH: "ANIM_BEHOLDER_SOUTH",
  ANIM_BEHOLDER_EAST: "ANIM_BEHOLDER_EAST",
  ANIM_BEHOLDER_WEST: "ANIM_BEHOLDER_WEST",

  ANIM_FAERIE_NORTH: "ANIM_FAERIE_NORTH",
  ANIM_FAERIE_SOUTH: "ANIM_FAERIE_SOUTH",
  ANIM_FAERIE_EAST: "ANIM_FAERIE_EAST",
  ANIM_FAERIE_WEST: "ANIM_FAERIE_WEST",

  LAYER_GROUND: "LAYER_GROUND",
  LAYER_PROPS: "LAYER_PROPS",

  MAP_DUNGEON: "MAP_DUNGEON",

  IMAGE_PANE: "IMAGE_PANE",
};

export const types: StringConstants = {
  PLAYER: "PLAYER",
  MONSTER: "MONSTER",
  DOOR: "DOOR",
  CHEST: "CHEST",
  OTHER: "OTHER",
};

export const facings: StringConstants = {
  NORTH: "NORTH",
  SOUTH: "SOUTH",
  EAST: "EAST",
  WEST: "WEST",
};

export const dungeonSprites: NumberConstants = {
  DOOR_CLOSED: 160,
  DOOR_OPEN: 161,
};
